---
- hosts: "{{ hosts }}"
  remote_user: "{{ remote_user }}"
  tasks:
    - name: update frontend code
      shell: git -C {{ frontend_root }} pull https://{{ git_username }}:{{ git_password }}@{{ frontend_repo }} {{ frontend_branch }}
      notify:
        - restart frontend
  handlers:
    - name: restart frontend
      shell: 'supervisorctl restart expression-frontend:'
