---
- hosts: expression-webservers
  tasks:
  - name: update database
    shell: gomigrate -database postgres://{{username}}:{{password}}@localhost:5432/golf?sslmode=disable -path $HOME/go/src/github.com/limen/fargo/migrations up

