---
- hosts: "{{ hosts }}"
  remote_user: "{{ remote_user }}"
  tasks:
    - name: update backend code
      shell: git -C {{ backend_root  }} pull https://{{ git_username }}:{{ git_password }}@{{ backend_repo }} {{ backend_branch }}
      notify:
        - restart backend
  handlers:
    - name: restart backend
      shell: 'supervisorctl restart expression-backend:'
